[build]
  command = "cd frontend && npm ci && npm run build"
  publish = "frontend/build"

[build.environment]
  GENERATE_SOURCEMAP = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://raw-minne-multisportsandevents-7f82c207.koyeb.app/api/:splat"
  status = 200