[build]
  base = "frontend"
  publish = "build"
  command = "npm run build"
  functions = ""

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "8"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API proxy for production
[[redirects]]
  from = "/api/*"
  to = "https://raw-minne-multisportsandevents-7f82c207.koyeb.app/api/:splat"
  status = 200
  force = false