[build]
  command = "cd frontend && npm install --no-audit --no-fund && npm run build"
  publish = "./frontend/build"

[build.environment]
  GENERATE_SOURCEMAP = "false"

## IMPORTANT: Place API proxy BEFORE SPA fallback so Netlify forwards API calls to Koyeb
[[redirects]]
  from = "/api/*"
  to = "https://raw-minne-multisportsandevents-7f82c207.koyeb.app/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

## Headers: aggressively cache hashed assets, but allow quick favicon/manifest refresh via query param versions
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/playaxis-icon.png"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=3600"