[build]
  base = "frontend"
  publish = "frontend/build"
  command = "npm run build"

[build.environment]
  # Stop shipping source maps (also reduces secret scanning surface)
  GENERATE_SOURCEMAP = "false"
  # Tell Netlify secret scanner to ignore this env var key
  SECRETS_SCAN_OMIT_KEYS = "WEATHER_API_URL"

# Single-page app routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Proxy API to your Koyeb app
[[redirects]]
  from = "/api/*"
  to = "https://raw-minne-multisportsandevents-7f82c207.koyeb.app/api/:splat"
  status = 200