[[redirects]]
  from = "/*"
  to = "/public/index.html"
  status = 200

[build]
  base = "frontend"
  publish = "/build"
  command = "npm run build"

[build.environment]
  SECRETS_SCAN_ENABLED = "false"