services:
  # FastAPI Backend Service
  - type: web
    name: multisportapp-backend
    runtime: python
    repo: https://github.com/OliverPerrin/MultiSportApp.git # This will be auto-filled by Render
    branch: main
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: /health # Assuming you have a health check endpoint
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: multisportapp-db
          property: connectionString
      - key: JWT_SECRET
        sync: false # Add in Render Dashboard
      - key: TWITCH_CLIENT_ID
        sync: false # Add in Render Dashboard
      - key: TWITCH_CLIENT_SECRET
        sync: false # Add in Render Dashboard
      - key: SPORTSDATA_API_KEY
        sync: false # Add in Render Dashboard
      - key: OPENWEATHER_API_KEY
        sync: false # Add in Render Dashboard

  # Example Key-Value Store (replace with your actual requirement)
  - type: keyvalue
    name: multisportapp-db
    plan: free # Use 'starter' for production apps. Free tier may sleep.
    ipAllowList: [] # Add allowed IPs here, empty array allows all